### ISSUE TITLE
Add license comments on all source files

### ISSUE THREAD

**Issue by idokleinman** [spark/spark-sdk-ios#11]
<a href="https://github.com/idokleinman"><img src="https://avatars.githubusercontent.com/u/6490062?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [idokleinman](https://github.com/idokleinman)**
_Saturday Jan 10, 2015 at 01:26 GMT_
_Originally opened as https://github.com/spark/mobile-sdk-ios/issues/26_

---

**Comment by idokleinman** [comment]
<a href="https://github.com/zsup"><img src="https://avatars.githubusercontent.com/u/929333?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zsup](https://github.com/zsup)**
_Saturday Jan 10, 2015 at 01:43 GMT_

---

Apache license, please!

**Comment by idokleinman** [comment]
<a href="https://github.com/idokleinman"><img src="https://avatars.githubusercontent.com/u/6490062?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [idokleinman](https://github.com/idokleinman)**
_Monday Jan 12, 2015 at 03:06 GMT_

---

Will do thanks for the input, wasn't sure about this one

**Comment by idokleinman** [comment]
<a href="https://github.com/zsup"><img src="https://avatars.githubusercontent.com/u/929333?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zsup](https://github.com/zsup)**
_Monday Jan 12, 2015 at 05:01 GMT_

---

sure thing. although actually now that I think about it, maybe we want this to be LGPL? @towynlin, what do you think?

Typically our approach is LGPL licenses to libraries and Apache for any example application code. LGPL ensures that users contribute improvements back to us. I think we could go either way here; on one hand it's a library so that would suggest LGPL, but on the other hand I would be comfortable allowing people to use this for non-Spark purposes (the set-up process stuff may be useful). Would love input from others

**Comment by idokleinman** [comment]
<a href="https://github.com/towynlin"><img src="https://avatars.githubusercontent.com/u/3389?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [towynlin](https://github.com/towynlin)**
_Monday Jan 12, 2015 at 07:19 GMT_

---

I don't have a strong opinion here. Either Apache or LGPL would be fine. The biggest difference I think is that LGPL would require a developer using the SDK to share the source code of any changes they make to the SDK (not of the app in which they use it). Apache would let them change the SDK behavior without sharing the source of those changes.

I'd lean slightly toward LGPL as a sense of assurance of high quality of Spark-powered apps as well as community spirit.

**Comment by idokleinman** [comment]
<a href="https://github.com/idokleinman"><img src="https://avatars.githubusercontent.com/u/6490062?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [idokleinman](https://github.com/idokleinman)**
_Tuesday Jan 13, 2015 at 02:27 GMT_

---

LGPL 2.1 or 3.0?
http://choosealicense.com/licenses/lgpl-2.1/
vs
http://choosealicense.com/licenses/lgpl-3.0/

**Comment by ghost** [comment]
The problem with LGPL is that the license is incompatible with apps distributed through the App Store.

**Comment by idokleinman** [comment]
All files/SDKs are now Apache 2.0 license
