### ISSUE TITLE
Sending ["D7",1] does not light the LED

### ISSUE THREAD

**Issue by ashu1702** [spark/spark-sdk-ios#23]
I am doing this in my iOS app:
let funcArgs = ["D7",1]
        myPhoton!.callFunction("digitalwrite", withArguments: funcArgs) { (resultCode : NSNumber!, error : NSError!) -> Void in
            print(resultCode)
            if (error == nil) {
                println("LED on D7 successfully turned on")
            }
        }
But the resultCode i am getting is -2 and no error. But for some reason the LED is not lighting. On the other hand when i am using the Tinker app it works perfectly.

Can some one please help.

Thanks,

**Comment by dmiddlecamp** [comment]
Hi @ashu1702 ,

  I think the digitalwrite function expects one argument as a string, maybe try:

```
let funcArgs = ["D7,HIGH"]
```

**Comment by ashu1702** [comment]
Yup.Figured that out. In example they still have ["D7",1]
Thanks,
