### ISSUE TITLE
Pod install fails

### ISSUE THREAD

**Issue by reallylongaddress** [spark/spark-sdk-ios#25]
![screen shot 2015-09-28 at 5 10 50 pm](https://cloud.githubusercontent.com/assets/84589/10150219/fd0895dc-6603-11e5-8ed8-ba3ccb900545.png)

**Comment by idokleinman** [comment]
Is this still an issue?

**Comment by idokleinman** [comment]
Sorry can't reproduce it, might be something with your cocoapods version
