### ISSUE TITLE
Photon setup crash on “Check for internet connectivity” 

### ISSUE THREAD

**Issue by williamhqs** [spark/spark-sdk-ios#27]
After choose your own wifi network and input the password it goes into this page and crash on "Check for interest connectivity"

![2 pic](https://cloud.githubusercontent.com/assets/354829/10875504/24b466da-816e-11e5-906f-2eeb9a3498d4.jpg)

What i do is just put these two lines into the button action:

```
       let setupController = SparkSetupMainController()
        self.presentViewController(setupController, animated: true, completion: nil)
```

log error is:

```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'data parameter is nil'
```

Crashes failure in this function:
`-(void)getDevices:(void (^)(NSArray *sparkDevices, NSError *error))completion`
<img width="717" alt="screen shot 2015-11-02 at 11 15 05 am" src="https://cloud.githubusercontent.com/assets/354829/10875673/34bb3e1c-8170-11e5-9da8-ec150f1ef526.png">

**Comment by idokleinman** [comment]
Thanks for reporting, I'll look into it.
Does it happen always or only on some cases?

**Comment by williamhqs** [comment]
@idokleinman I am stuck on here can't get into any other parts. For login part familiar errors happens too, seems not in this function. I posted on community too. Thanks for your helping to check the reasons.

**Comment by williamhqs** [comment]
Any progress?

**Comment by idokleinman** [comment]
Yes, I'll post an update today.
It's a really simple issue - I added better error reporting so user can see a log of the failed response body (that contains more context for the error) - but it back-fired because errorData might be null on some cases - a simple if (errorData) check fixes this.

**Comment by idokleinman** [comment]
@williamhqs  OK, please update iOS Cloud SDK to v0.3.3 (run `pod update`) and let me know if you still have any issues. Thanks
