### ISSUE TITLE
Cannot import with Carthage

### ISSUE THREAD

**Issue by crenwick** [spark/spark-sdk-ios#37]
Getting a `Could not build Objective-C module 'ParticleSDK'` error on my `import ParticleSDK` line. 
This also causes the `#import "SparkEvent.h"` line in `SparkDevice.h` file to throw the error `'SparkEvent.h file not found`

Cartfile:

```
github "spark/spark-sdk-ios" ~> 0.4.1
```

Running `$ carthage update --no-use-binaries --platform iOS`.

Notes:
- With no changes to the Cartfile or command, `import AFNetworking` throws no errors.
- This error effects https://github.com/spark/spark-setup-ios. In other words, I cannot use that library with Carthage because it requires me to call `SparkCloud` in code, which requires me to have `import ParticleSDK`. But interestingly, `import ParticleDeviceSetupLibrary` throws no errors :+1:

**Comment by idokleinman** [comment]
This was WIP today. Now everything is fixed, try again.
Both Carthage AND cocoapods are v0.4+ and play nicely together.

**Comment by crenwick** [comment]
👍

Nice. Thanks for the fix @idokleinman . Got it working in a sample project in just a few minutes.

**Comment by idokleinman** [comment]
Glad to hear! I'll be uploading a Carthage-based simple example app today and announcing the new features in the community.
